apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: Exposes and load balances the application pods
    labels:
      app: sigstore
      template: sigstore
    name: sigstore
  spec:
    ports:
    - name: web
      port: 8080
      targetPort: 8080
    selector:
      name: sigstore
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: sigstore
      template: sigstore
    name: sigstore
  spec:
    host: ""
    to:
      kind: Service
      name: sigstore
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      description: Defines how to deploy the application server
      template.alpha.openshift.io/wait-for-ready: "true"
    labels:
      app: sigstore
      template: sigstore
    name: sigstore
  spec:
    replicas: 1
    selector:
      name: sigstore
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          name: sigstore
        name: sigstore
      spec:
        containers:
        - env: []
          image: registry.access.redhat.com/rhscl/httpd-24-rhel7:latest
          name: httpd
          ports:
          - containerPort: 8080
          resources:
            limits:
              memory: 512Mi
          securityContext:
            privileged: true
          volumeMounts:
          - mountPath: /var/www/html
            name: sigstore-volume
        nodeSelector:
          type: builder
        serviceAccountName: imagemanager
        volumes:
        - hostPath:
            path: /var/lib/containers/sigstore/
          name: sigstore-volume
